stages:
  - build
  - deploy

build:
  stage: build
  image: node:21-alpine
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - .next/

deploy:
  stage: deploy
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE .
    - docker push $CI_REGISTRY_IMAGE
  only:
    - staging
